In [31]:
#import required libraries
import pandas as pd

In [32]:
#loading the dataset
df=pd.read_csv("data\\raw_data.csv")
#displaying The first five rows in the datset
df.head()

,title,price,star_rating,availability,category
0,It's Only the Himalayas,£45.17,Two,In stock,Travel
1,Full Moon over Noah’s Ark: An Odyssey to Mount...,£49.43,Four,In stock,Travel
2,See America: A Celebration of Our National Par...,£48.87,Three,In stock,Travel
3,Vagabonding: An Uncommon Guide to the Art of L...,£36.94,Two,In stock,Travel
4,Under the Tuscan Sun,£37.33,Three,In stock,Travel

In [33]:
df.shape

(73, 5)

In [34]:
#Displaying information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         73 non-null     str
 1   price         73 non-null     str
 2   star_rating   73 non-null     str
 3   availability  73 non-null     str
 4   category      73 non-null     str
dtypes: str(5)
memory usage: 3.0 KB

In [35]:
#ch3cking for null values in the dataset
df.isnull().sum()

title           0
price           0
star_rating     0
availability    0
category        0
dtype: int64

***Cleaning Price column***

In [36]:
#removing £ in price column and converting it to float in new column price_gbp
df['price_gbp']=df['price'].str.replace('£','').str.strip().astype(float)

In [37]:
df.head()

,title,price,star_rating,availability,category,price_gbp
0,It's Only the Himalayas,£45.17,Two,In stock,Travel,45.17
1,Full Moon over Noah’s Ark: An Odyssey to Mount...,£49.43,Four,In stock,Travel,49.43
2,See America: A Celebration of Our National Par...,£48.87,Three,In stock,Travel,48.87
3,Vagabonding: An Uncommon Guide to the Art of L...,£36.94,Two,In stock,Travel,36.94
4,Under the Tuscan Sun,£37.33,Three,In stock,Travel,37.33

In [38]:
#checking values in star_rating column
df['star_rating'].unique()

<StringArray>
['Two', 'Four', 'Three', 'One', 'Five']
Length: 5, dtype: str

In [39]:
#Converting star_ratings text into integers(1-5)
text_ratings={
  "One":1,
  "Two":2,
  "Three":3,
  "Four":4,
  "Five":5
}
df['rating']=df['star_rating'].replace(text_ratings).astype(int)

In [40]:
# Create a boolean column:
# True  -> Book is in stock
# False -> Book is not in stock
df["in_stock"] = df["availability"].str.contains(
    "In stock",
    case=False,
    na=False
)

In [41]:
#converting Gbp to Inr in new column price_inr
gbp_to_inr=105.50
df['price_inr']=(df['price_gbp']*gbp_to_inr).round(2)

In [42]:
df.head()

,title,price,star_rating,availability,category,price_gbp,rating,in_stock,price_inr
0,It's Only the Himalayas,£45.17,Two,In stock,Travel,45.17,2,True,4765.44
1,Full Moon over Noah’s Ark: An Odyssey to Mount...,£49.43,Four,In stock,Travel,49.43,4,True,5214.86
2,See America: A Celebration of Our National Par...,£48.87,Three,In stock,Travel,48.87,3,True,5155.78
3,Vagabonding: An Uncommon Guide to the Art of L...,£36.94,Two,In stock,Travel,36.94,2,True,3897.17
4,Under the Tuscan Sun,£37.33,Three,In stock,Travel,37.33,3,True,3938.31

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         73 non-null     str
 1   price         73 non-null     str
 2   star_rating   73 non-null     str
 3   availability  73 non-null     str
 4   category      73 non-null     str
 5   price_gbp     73 non-null     float64
 6   rating        73 non-null     int64
 7   in_stock      73 non-null     bool
 8   price_inr     73 non-null     float64
dtypes: bool(1), float64(2), int64(1), str(5)
memory usage: 4.8 KB

In [44]:
#Dropping the columns which are not required for analysis
df.drop(columns=["price","star_rating","availability"],inplace=True)

In [45]:
df.head()

,title,category,price_gbp,rating,in_stock,price_inr
0,It's Only the Himalayas,Travel,45.17,2,True,4765.44
1,Full Moon over Noah’s Ark: An Odyssey to Mount...,Travel,49.43,4,True,5214.86
2,See America: A Celebration of Our National Par...,Travel,48.87,3,True,5155.78
3,Vagabonding: An Uncommon Guide to the Art of L...,Travel,36.94,2,True,3897.17
4,Under the Tuscan Sun,Travel,37.33,3,True,3938.31

In [46]:
#save cleaned Dataset
df.to_csv("data\\cleaned_data.csv",index=False)
print("Dataset saved Successfully")

Dataset saved Successfully

In [47]:
#final dataset check
# Final dataset check
print("Final dataset shape:", df.shape)
print("\nFinal columns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

print("\nData types:")
print(df.dtypes)

Final dataset shape: (73, 6)

Final columns:
['title', 'category', 'price_gbp', 'rating', 'in_stock', 'price_inr']

Missing values:
title        0
category     0
price_gbp    0
rating       0
in_stock     0
price_inr    0
dtype: int64

Data types:
title            str
category         str
price_gbp    float64
rating         int64
in_stock        bool
price_inr    float64
dtype: object