In [57]:
#import required libraries
import pandas  as pd 
import sqlite3 as sql

In [58]:
db_path="database/books.db"

#connecting to the database
connect=sql.connect(db_path)

print("Database Successfully Connected to SQLite")

Database Successfully Connected to SQLite

In [59]:
# Display all tables in the SQLite database
tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table'",
    connect
)

tables

       name
0  category
1     books

***QUERIES :***




***1. Query books with a rating greater than or equal to 4***

In [60]:
query="select title,rating,price_inr from books where rating>=4"
result=pd.read_sql_query(query,connect)
print(result)

                                                title  rating  price_inr
0   Full Moon over Noah’s Ark: An Odyssey to Mount...       4    5214.86
1                    A Year in Provence (Provence #1)       4    6000.84
2                  1,000 Places to See Before You Die       5    2751.44
3                                       Sharp Objects       4    5045.01
4                                 The Past Never Ends       4    5960.75
5     The Murder of Roger Ackroyd (Hercule Poirot #4)       4    4652.55
6              A Time of Torment (Charlie Parker #14)       5    5100.92
7   Murder at the 42nd Street Library (Raymond Amb...       4    5734.98
8                         Private Paris (Private #10)       5    5022.85
9                        We Love You, Charlie Freeman       5    5303.48
10                                             Thirst       5    1821.98
11                                    The Vacationers       4    4446.82
12               The Regional Office Is Under Attack!       5    5418.48
13           Finders Keepers (Bill Hodges Trilogy #2)       5    5647.42
14                                    The Time Keeper       5    2941.34
15                              The Testament of Mary       4    5556.68
16                                              Shtum       4    5891.12
17  The Most Perfect Thing: Inside (and Outside) a...       4    4532.28
18  Immunity: How Elie Metchnikoff Changed the Cou...       5    6051.48
19  Sorting the Beef from the Bull: The Science of...       4    4720.07
20                              The Origin of Species       4    1056.06
21  The Elegant Universe: Superstrings, Hidden Dim...       4    1374.66
22  The Disappearing Spoon: And Other True Tales o...       5    6050.42
23                     Seven Brief Lessons on Physics       4    3228.30
24                   Psycho: Sanitarium (Psycho #1.5)       5    3900.34
25                                Dracula the Un-Dead       5    3758.96
26                    Night Shift (Night Shift #1-20)       4    1345.12
27                                     Needful Things       4    5012.30
28                                       'Salem's Lot       4    5228.58

***2. Display Unique rating values***

In [61]:
query = '''
SELECT DISTINCT rating
FROM books
ORDER BY rating ASC
'''

result = pd.read_sql_query(query, connect)

print(result)

   rating
0       1
1       2
2       3
3       4
4       5

***3. Display the top 5 most expensive books based on price_gbp.***

In [62]:
query="select book_id,title,price_gbp from books order by price_gbp DESC limit 5"
result=pd.read_sql_query(query,connect)
print(result)

   book_id                                              title  price_gbp
0       26                      Boar Island (Anna Pigeon #19)      59.48
1       72                                          The Stand      57.86
2       45  Immunity: How Elie Metchnikoff Changed the Cou...      57.36
3       54  The Disappearing Spoon: And Other True Tales o...      57.35
4        8                   A Year in Provence (Provence #1)      56.88

***4. Display the book ID, title, rating, and price of all books whose price is between £20 and £40, sorted by price from highest to lowest.***

In [63]:
query="select book_id,title,rating,price_gbp from books where price_gbp between 20 and 40 order by price_gbp DESC"
result=pd.read_sql_query(query,connect)
print(result)

    book_id                                              title  rating  \
0        58                                           Security       2
1        10          Neither Here nor There: Travels in Europe       3
2        47  Tipping Point for Planet Earth: How Close Are ...       1
3         5                               Under the Tuscan Sun       3
4        63                   Psycho: Sanitarium (Psycho #1.5)       5
5         4  Vagabonding: An Uncommon Guide to the Art of L...       2
6        66                                Dracula the Un-Dead       5
7        24                                        Most Wanted       3
8        69                                             Misery       2
9        56                     Seven Brief Lessons on Physics       4
10        7                           The Great Railway Bazaar       1
11       57                                   The Selfish Gene       1
12       49  Diary of a Citizen Scientist: Chasing Tiger Be...       1
13       37                                    The Time Keeper       5
14       27                                          The Widow       2
15       22                   Poisonous (Max Revere Novels #3)       3
16       41                       Still Life with Bread Crumbs       3
17       11                 1,000 Places to See Before You Die       5
18       39                The First Hostage (J.B. Collins #2)       3
19       55  Surely You're Joking, Mr. Feynman!: Adventures...       2
20       70                                                 It       3
21       60                                          The Loney       1
22       65                    Red Dragon (Hannibal Lecter #1)       3
23        9  The Road to Little Dribbling: Adventures of an...       1
24       59                                    Follow You Home       1
25       33                             Tuesday Nights in 1980       2

    price_gbp
0       39.25
1       38.95
2       37.55
3       37.33
4       36.97
5       36.94
6       35.63
7       35.28
8       34.79
9       30.60
10      30.54
11      29.45
12      28.41
13      27.88
14      27.26
15      26.80
16      26.41
17      26.08
18      25.85
19      25.83
20      25.01
21      23.40
22      23.37
23      23.21
24      21.36
25      21.04

***5. Display the book title, category name, rating, and price of books that have a rating of 4 or higher. Sort the results first by category name alphabetically and then by price from highest to lowest.***

In [64]:
query='''
select b.title,c.category_name,b.rating,b.price_gbp
from books as b 
JOIN 
category as c 
on 
b.category_id=c.category_id
where b.rating>=4 
order by c.category_name ASC,b.price_gbp DESC'''
result=pd.read_sql_query(query,connect)
print(result)

                                                title category_name  rating  \
0                                               Shtum       Fiction       4
1            Finders Keepers (Bill Hodges Trilogy #2)       Fiction       5
2                               The Testament of Mary       Fiction       4
3                The Regional Office Is Under Attack!       Fiction       5
4                        We Love You, Charlie Freeman       Fiction       5
5                         Private Paris (Private #10)       Fiction       5
6                                     The Vacationers       Fiction       4
7                                     The Time Keeper       Fiction       5
8                                              Thirst       Fiction       5
9                                        'Salem's Lot        Horror       4
10                                     Needful Things        Horror       4
11                   Psycho: Sanitarium (Psycho #1.5)        Horror       5
12                                Dracula the Un-Dead        Horror       5
13                    Night Shift (Night Shift #1-20)        Horror       4
14                                The Past Never Ends       Mystery       4
15  Murder at the 42nd Street Library (Raymond Amb...       Mystery       4
16             A Time of Torment (Charlie Parker #14)       Mystery       5
17                                      Sharp Objects       Mystery       4
18    The Murder of Roger Ackroyd (Hercule Poirot #4)       Mystery       4
19  Immunity: How Elie Metchnikoff Changed the Cou...       Science       5
20  The Disappearing Spoon: And Other True Tales o...       Science       5
21  Sorting the Beef from the Bull: The Science of...       Science       4
22  The Most Perfect Thing: Inside (and Outside) a...       Science       4
23                     Seven Brief Lessons on Physics       Science       4
24  The Elegant Universe: Superstrings, Hidden Dim...       Science       4
25                              The Origin of Species       Science       4
26                   A Year in Provence (Provence #1)        Travel       4
27  Full Moon over Noah’s Ark: An Odyssey to Mount...        Travel       4
28                 1,000 Places to See Before You Die        Travel       5

    price_gbp
0       55.84
1       53.53
2       52.67
3       51.36
4       50.27
5       47.61
6       42.15
7       27.88
8       17.27
9       49.56
10      47.51
11      36.97
12      35.63
13      12.75
14      56.50
15      54.36
16      48.35
17      47.82
18      44.10
19      57.36
20      57.35
21      44.74
22      42.96
23      30.60
24      13.03
25      10.01
26      56.88
27      49.43
28      26.08

***6.Display all books whose price_gbp is greater than the average price of all books. 
Show the book title, category name, price, and rating. Sort the results by price from highest to lowest.***

In [65]:
query = '''
SELECT 
    b.title,
    c.category_name,
    b.price_gbp,
    b.rating

FROM books AS b

JOIN category AS c
ON b.category_id = c.category_id

WHERE b.price_gbp > (
    SELECT AVG(price_gbp)
    FROM books
)

ORDER BY b.price_gbp DESC
'''

result = pd.read_sql_query(query, connect)

print(result)

                                                title category_name  \
0                       Boar Island (Anna Pigeon #19)       Mystery
1                                           The Stand        Horror
2   Immunity: How Elie Metchnikoff Changed the Cou...       Science
3   The Disappearing Spoon: And Other True Tales o...       Science
4                    A Year in Provence (Provence #1)        Travel
5                                 The Past Never Ends       Mystery
6   The Fabric of the Cosmos: Space, Time, and the...       Science
7                                               Shtum       Fiction
8   Murder at the 42nd Street Library (Raymond Amb...       Mystery
9                      The Last Mile (Amos Decker #2)       Mystery
10  The Murder That Never Was (Forensic Instincts #5)       Fiction
11           Finders Keepers (Bill Hodges Trilogy #2)       Fiction
12                              The Testament of Mary       Fiction
13               The Regional Office Is Under Attack!       Fiction
14                       We Love You, Charlie Freeman       Fiction
15                                         Soumission       Fiction
16                                       'Salem's Lot        Horror
17                        The Girl with All the Gifts        Horror
18  Full Moon over Noah’s Ark: An Odyssey to Mount...        Travel
19  See America: A Celebration of Our National Par...        Travel
20   Can You Keep a Secret? (Fear Street Relaunch #4)        Horror
21             A Time of Torment (Charlie Parker #14)       Mystery
22                                      Sharp Objects       Mystery
23                        Private Paris (Private #10)       Fiction
24                                     Needful Things        Horror
25                                   Take Me with You       Fiction
26                            It's Only the Himalayas        Travel
27  Sorting the Beef from the Bull: The Science of...       Science
28                                 A Summer In Europe        Travel
29    The Murder of Roger Ackroyd (Hercule Poirot #4)       Mystery
30  The Most Perfect Thing: Inside (and Outside) a...       Science
31                                    The Vacationers       Fiction
32                             My Name Is Lucy Barton       Fiction
33                      Doctor Sleep (The Shining #2)        Horror
34                                           Security        Horror
35          Neither Here nor There: Travels in Europe        Travel
36  Tipping Point for Planet Earth: How Close Are ...       Science
37                               Under the Tuscan Sun        Travel
38                   Psycho: Sanitarium (Psycho #1.5)        Horror
39  Vagabonding: An Uncommon Guide to the Art of L...        Travel

    price_gbp  rating
0       59.48       3
1       57.86       2
2       57.36       5
3       57.35       5
4       56.88       4
5       56.50       4
6       55.91       1
7       55.84       4
8       54.36       4
9       54.21       2
10      54.11       3
11      53.53       5
12      52.67       4
13      51.36       5
14      50.27       5
15      50.10       1
16      49.56       4
17      49.47       3
18      49.43       4
19      48.87       3
20      48.64       1
21      48.35       5
22      47.82       4
23      47.61       5
24      47.51       4
25      45.21       3
26      45.17       2
27      44.74       4
28      44.34       2
29      44.10       4
30      42.96       4
31      42.15       4
32      41.56       1
33      40.12       2
34      39.25       2
35      38.95       3
36      37.55       1
37      37.33       3
38      36.97       5
39      36.94       2

***7. Find the category or categories whose average book price is greater than the overall average book price. 
For those categories, display the category name, total number of books, average price, highest price, and lowest price. Sort the results by average price from highest to lowes***

In [66]:
query = '''
SELECT 
    c.category_name,
    COUNT(b.book_id) AS total_books,
    AVG(b.price_gbp) AS average_price,
    MAX(b.price_gbp) AS highest_price,
    MIN(b.price_gbp) AS lowest_price

FROM books AS b

JOIN category AS c
ON b.category_id = c.category_id

GROUP BY c.category_name

HAVING AVG(b.price_gbp) > (
    SELECT AVG(price_gbp)
    FROM books
)

ORDER BY average_price DESC
'''

result = pd.read_sql_query(query, connect)

print(result)

  category_name  total_books  average_price  highest_price  lowest_price
0       Fiction           16      41.428750          55.84         17.27
1        Travel           11      39.794545          56.88         23.21

***8. Find categories that have more than 10 books. Display the category name, total number of books, and average book price. Only include categories whose average rating is 3 or higher. Sort the results by total number of books from highest to lowest.***

In [67]:
query = '''
SELECT 
    c.category_name,
    COUNT(b.book_id) AS total_books,
    AVG(b.price_gbp) AS average_price

FROM books AS b

JOIN category AS c
ON b.category_id = c.category_id

GROUP BY c.category_name

HAVING COUNT(b.book_id) > 10
AND AVG(b.rating) >= 3

ORDER BY total_books DESC
'''
result=pd.read_sql_query(query,connect)
print(result)

  category_name  total_books  average_price
0       Fiction           16       41.42875

***9. Reproducing SQL JOIN Using Pandas merge()***

In [68]:
# Load the books table into a DataFrame
books_df = pd.read_sql_query(
    "SELECT * FROM books",
    connect
)

# Load the category table into a DataFrame
category_df = pd.read_sql_query(
    "SELECT * FROM category",
    connect
)

In [69]:
# Perform an inner join using category_id
merged_df = pd.merge(
    books_df,
    category_df,
    on="category_id",
    how="inner"
)

merged_df.head()

,book_id,title,price_gbp,rating,in_stock,price_inr,category_id,category_name
0,1,It's Only the Himalayas,45.17,2,1,4765.44,1,Travel
1,2,Full Moon over Noah’s Ark: An Odyssey to Mount...,49.43,4,1,5214.86,1,Travel
2,3,See America: A Celebration of Our National Par...,48.87,3,1,5155.78,1,Travel
3,4,Vagabonding: An Uncommon Guide to the Art of L...,36.94,2,1,3897.17,1,Travel
4,5,Under the Tuscan Sun,37.33,3,1,3938.31,1,Travel

In [70]:
# SQL query to join books and category tables
sql_join = '''
SELECT 
    b.title,
    c.category_name,
    b.rating,
    b.price_gbp

FROM books AS b

JOIN category AS c
ON b.category_id = c.category_id
'''

# Execute the SQL JOIN query
sql_result = pd.read_sql_query(sql_join, connect)

sql_result.head()

,title,category_name,rating,price_gbp
0,It's Only the Himalayas,Travel,2,45.17
1,Full Moon over Noah’s Ark: An Odyssey to Mount...,Travel,4,49.43
2,See America: A Celebration of Our National Par...,Travel,3,48.87
3,Vagabonding: An Uncommon Guide to the Art of L...,Travel,2,36.94
4,Under the Tuscan Sun,Travel,3,37.33

In [71]:
# Select the same columns from the merged DataFrame
pandas_result = merged_df[
    [
        "title",
        "category_name",
        "rating",
        "price_gbp"
    ]
]

pandas_result.head()

,title,category_name,rating,price_gbp
0,It's Only the Himalayas,Travel,2,45.17
1,Full Moon over Noah’s Ark: An Odyssey to Mount...,Travel,4,49.43
2,See America: A Celebration of Our National Par...,Travel,3,48.87
3,Vagabonding: An Uncommon Guide to the Art of L...,Travel,2,36.94
4,Under the Tuscan Sun,Travel,3,37.33

In [72]:
# Check whether both DataFrames contain the same data
sql_result.equals(pandas_result)

True

In [73]:
# Close the SQLite database connection
connect.close()

print("Database connection closed successfully!")

Database connection closed successfully!